db:
    image: mysql:5.5.47
    ports:
        - "3306:3306"
    environment:
        #MYSQL_USER: root
        #MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: myboard

web:
    image: brunolellis/myboard:latest
    ports:
        - "8080:8080"
    links:
        - db:db
